### ISSUE TITLE
Handling encrypted content

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/webpub-manifest#1]
In EPUB, encrypted content is declared in `encryption.xml` with the following information (as of EPUB 3.1):

- algorithm used to encrypt the resource
- how the resource is stored in the ZIP container (Store or deflate)
- original size of the resource

In addition to these information, other relevant info are missing:

- identifier for a specific DRM scheme
- profile for a specific DRM (very useful for LCP)

In this new manifest, using the [Properties Object](https://github.com/readium/webpub-manifest/blob/master/properties.md) could be a good fit to provide that info.

**Comment by HadrienGardeur** [comment]
This is now part of the [EPUB extension](https://github.com/readium/webpub-manifest/blob/master/extensions/epub.md) to the spec.

**Comment by llemeurfr** [comment]
As currently specified, each spine item will get a properties/encrypted object. As an ebook is protected in a consistent manner, these objects will be redondant. We may study a way to simplify the notation, an move the common information in a common place (but I know such normalization creates references, and this is another type of problem for the developers; in fact the current de-normalization may be simpler if this is a global rule in the serialization model). 
Also, in the sample, there is mention of the encryption algorithm. But this algorithm is already specified by the encryption profile in the LCP use case at least, therefore I think it must be removed from this sample.

**Comment by HadrienGardeur** [comment]
I disagree about this being completely redundant:

- in LCP not all resources are encrypted
- we also use this object for font obfuscation where only a few resources are obfuscated

It is IMO much easier to have this information at a resource level, not just in the in-memory model but also in the JSON manifest.
Also, keep in mind that this is not just the output of the streamer, but also a manifest that could be distributed in a container.

A DRM can also potentially use multiple algorithm, one could argue that the same is true about a different encryption profile in LCP. 
That's the reason why the algorithm is specified in this example.

**Comment by llemeurfr** [comment]
I'm ok with the redundancy, if others don't mind either. 
But for the LCP sample I insist that the algorithm should be removed. There is no example of diverse algorithms in one LCP profile, so let's not confuse implementers.

**Comment by HadrienGardeur** [comment]
We've already discussed this possibility for LCP before, even though you've dropped GCM in the meantime, I would highly prefer to remain consistent and keep this value.

Keep in mind too that this is simply extracted from `encryption.xml` at this point, where the algorithm is always included for LCP.
The `algorithm` key is pretty much the only required one, the rest is all optional.

**Comment by danielweck** [comment]
I believe that each encrypted resource ("link" JSON object) **must** declare an `algorithm` URI (`EncryptionMethod` in XML enc). A typical reading system or content processor does not infer low-level encryption algorithms from the "profile" layer of indirection (which is really only a high-level concept used to verify that the declared per-resource algorithm-URIs are indeed conformant). 

Conversely, the repeated `profile` URI on each resource link is indeed totally redundant, as it applies to the publication as a whole. The repeated `scheme` URI is ; strictly-speaking ; useful on a per-resource basis, because it declares clearly how the decryption key can be obtained (`RetrievalMethod` in XML enc). But it is kind of redundant unless a weird DRM allows content resources to be encrypted with different algos + key-retrieval schemes, within the same profile (publication instance / EPUB container).

See:
https://readium.github.io/readium-lcp-specification/#22-using-meta-infencryptionxml-for-lcp

**Comment by HadrienGardeur** [comment]
Which is why the `algorithm` is the only required key.

But since I don't want to force reading systems to infer anything, I'd rather be redundant and also provide `scheme` and `profile` per resource.

In general,  the goal is to be simple and avoid redundancy, because we want to make human authoring less painful than with EPUB.
But this is a perfect counter-example: no one will ever author this information manually. In this case, consistency and machine-readability are the highest priorities.
