### ISSUE TITLE
JSON Schema - please clarify usage of publication subcollection

### ISSUE THREAD

**Issue by danielweck** [readium/webpub-manifest#18]
Hello @HadrienGardeur could you please provide an example of how the recursive `additionalProperties` / `subcollection.schema.json` gets "expanded" into a `publication` object? I am having a hard time translating this part of the schema into workable (TypeScript) code, especially with the recursively-introduced `metadata` and `links` data fields, and the array-of-objects/single-object/array-of-link "union type" design approach which creates several possible structural variants in the data model. Many thanks!

https://github.com/readium/webpub-manifest/blob/0ac78ab5c270a608c39b4b04fc90bd9b1d281896/schema/publication.schema.json#L64-L66

https://github.com/readium/webpub-manifest/blob/0ac78ab5c270a608c39b4b04fc90bd9b1d281896/schema/subcollection.schema.json#L1-L58

**Comment by HadrienGardeur** [comment]
This is part of the extensibility model of RWPM. Look at OPDS 2.0 for an example of how this is used through the use of an `images` subcollection.

Keep in mind that the JSON Schema has to be more flexible than the in-memory model that you're defining. In your case, all you need to do is:

- define `subCollections` as an array of collections
- each collection can contain `metadata` (an array of `otherMetadata`), `links` (an array of `Link`) and sub-collections (an array of collections)

If you encounter an array of strings while parsing, just add them in `links`. Otherwise, add `metadata` in `metadata`, `links` in `links` and everything else in `subCollections`.

**Comment by HadrienGardeur** [comment]
I'm also considering renaming `subcollection.schema.json` to something else. Maybe `core.schema.json` since this is the core model?

Every RWPM, OPDS 2.0 feed or publication should validate against that schema.
