### ISSUE TITLE
Add a ToC section

### ISSUE THREAD

**Issue by llemeurfr** [readium/webpub-manifest#2]
A ToC (Table of Contents) section has been added in the Readium-2 software, but there is no mention of it in this specification. 

Its source is an EPUB2 NCX file or an EPUB3 Navigation document.

**Comment by HadrienGardeur** [comment]
This was initially discussed on the issue tracker for Readium-2 and we agreed on a syntax.

I don't think that this will be added to the main specification here, I still have mixed feelings about this.

My plan is to either:

- add it to the EPUB extension (https://github.com/readium/webpub-manifest/blob/master/extensions/epub.md)
- or roll its own extension for it

Since I want the Readium Web Publication Manifest to be as universal as possible, I avoid putting too many EPUB specific features at this point, and isolate them through extensions.

Since the manifest has very good extensibility mechanism (metadata, collection roles, relationship values, properties), this is super easy to do.
